<a href="https://colab.research.google.com/github/Shravani-std/Deep-Learning/blob/main/Backpropogation_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df= pd.DataFrame([[8,8,4], [7,9,5], [6,10,6],[5,12,7]], columns=['cgpa', 'profile_score','lpa'])


In [ ]:
def init_para(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):
    parameters['w' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))* 0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

  return parameters


In [ ]:
init_para([2,2,1])

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def sigmoid(z):
  A = 1 / ( 1 + np.exp(-z))

  return A

In [ ]:
def linear_forward(A_prev, w, b):
  z = np.dot(w.T, A_prev) + b
  A = sigmoid(z)
  return A

In [ ]:
# Forward Propogation

def L_Layer_forward(X, parameters):
  A = X
  L = len(parameters) // 2

  for l in range(1, L+1):
    A_prev = A
    w1 = parameters['w' + str(l)]
    b = parameters['b' + str(l)]

    print("A"+ str(l - 1)+ " : ", A_prev)
    print("w" + str(l) + " : ", w1)
    print("b" + str(l) + " : ", b)
    print("--"*20)

    A = linear_forward(A_prev, w1, b)
    print("A" + str(l) + ": ", A)
    print( "**"*20 )

  return A, A_prev

In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = init_para([2,2,1])
L_Layer_forward(X, parameters)

A0 :  [[8]
 [8]]
w1 :  [[0.1 0.1]
 [0.1 0.1]]
b1 :  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1 :  [[0.83201839]
 [0.83201839]]
w2 :  [[0.1]
 [0.1]]
b2 :  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************


(array([[0.54150519]]),
 array([[0.83201839],
        [0.83201839]]))

In [ ]:
# Calculate loss

(y- 0.32)**2

np.float64(13.5424)

In [ ]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['w2'][0][0] = parameters['w2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['w2'][1][0] = parameters['w2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.0001 * (y - y_hat))

  parameters['w1'][0][0] = parameters['w1'][0][0] + (0.0001 * (y - y_hat)*parameters['w2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['w1'][0][1] = parameters['w1'][0][1] + (0.0001 * (y - y_hat)*parameters['w2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['w2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['w1'][1][0] = parameters['w1'][1][0] + (0.0001 * (y - y_hat)*parameters['w2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['w1'][1][1] = parameters['w1'][1][1] + (0.0001 * (y - y_hat)*parameters['w2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['w2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = init_para([2,2,1])

y_hat, A1 = L_Layer_forward(X, parameters)


A0 :  [[8]
 [8]]
w1 :  [[0.1 0.1]
 [0.1 0.1]]
b1 :  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1 :  [[0.83201839]
 [0.83201839]]
w2 :  [[0.1]
 [0.1]]
b2 :  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************


In [ ]:
y_hat = y_hat[0][0]
y_hat

np.float64(0.5415051895671072)

In [ ]:
A1

array([[0.83201839],
       [0.83201839]])

In [ ]:
parameters

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
# epochs Implementation
parameters = init_para([2,2,1])
epochs = 5

for j in range(epochs):
  loss = []  # Initialize loss list for each epoch
  for i in range(df.shape[0]):
    X =  df[['cgpa', 'profile_score']].values[i].reshape(-1,1) # Fixed: Access values before reshaping
    y = df[['lpa']].values[i][0]

    y_hat, A1 = L_Layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters, y, y_hat, A1, X)

    loss.append((y - y_hat) ** 2)

  print("Epoch: ", j+1, 'Loss - ', np.array(loss).mean())

A0 :  [[8]
 [8]]
w1 :  [[0.1 0.1]
 [0.1 0.1]]
b1 :  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1 :  [[0.83201839]
 [0.83201839]]
w2 :  [[0.1]
 [0.1]]
b2 :  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************
A0 :  [[7]
 [9]]
w1 :  [[0.10003878 0.10003878]
 [0.10003878 0.10003878]]
b1 :  [[4.84763268e-06]
 [4.84763268e-06]]
----------------------------------------
A1:  [[0.83210577]
 [0.83210577]]
****************************************
A1 :  [[0.83210577]
 [0.83210577]]
w2 :  [[0.10028775]
 [0.10028775]]
b2 :  [[0.00034585]]
----------------------------------------
A2:  [[0.54171428]]
****************************************
A0 :  [[ 6]
 [10]]
w1 :  [[0.10008267 0.10009521]
 [0.10008267 0.10009521]]
b1 :  [[1.11171434e-05]
 [1.11171434e-05]]
----------------------------------------
A1:  [[0.83220472]
 [0.83223273]]
****************************

# Using Keras

In [ ]:
import pandas as pd
import numpy as np

df= pd.DataFrame([[8,8,4], [7,9,5], [6,10,6],[5,12,7]], columns=['cgpa', 'profile_score','lpa'])


In [ ]:
import tensorflow
from tensorflow import keras
from keras.layers import Dense
from keras import Sequential

In [ ]:
model = Sequential()
model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(2, activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 2)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12 (48.00 B)

 Trainable params: 12 (48.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[-1.0486473 , -0.10288918],
        [-1.181135  , -0.3072564 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.13712883,  0.87515986],
        [ 0.09131694, -0.75910956]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)
model.build(input_shape=(None, 2)) # Explicitly build the model

In [ ]:
model.fit(df.iloc[:,0:-1].values, df.iloc[:,-1].values, epochs=75, verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 169.6979  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 185.1547 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 185.1532 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 172.1783 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 179.5525 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 152.3257 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 166.6083 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 153.6257 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.1285 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 160.1254 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 151.8160 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 136.8580 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 139.9520 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 124.3943 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 130.6947 
Epo