<a href="https://colab.research.google.com/github/Shravani-std/Deep-Learning/blob/main/Backpropogation_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df= pd.DataFrame([[8,8,4], [7,9,5], [6,10,6],[5,12,7]], columns=['cgpa', 'profile_score','lpa'])


In [ ]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
def init_para(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):
    parameters['w' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))* 0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

  return parameters


In [ ]:
init_para([2,2,1])

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def linear_forward(A_prev, w, b):
  z = np.dot(w.T, A_prev) + b

  return z

In [ ]:
# Forward Propogation

def L_Layer_forward(X, parameters):
  A = X
  L = len(parameters) // 2

  for l in range(1, L+1):
    A_prev = A
    w1 = parameters['w' + str(l)]
    b = parameters['b' + str(l)]

    print("A"+ str(l - 1)+ " : ", A_prev)
    print("w" + str(l) + " : ", w1)
    print("b" + str(l) + " : ", b)
    print("--"*20)

    A = linear_forward(A_prev, w1, b)
    print("A" + str(l) + ": ", A)
    print( "**"*20 )

  return A, A_prev

In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = init_para([2,2,1])
L_Layer_forward(X, parameters)

A0 :  [[8]
 [8]]
w1 :  [[0.1 0.1]
 [0.1 0.1]]
b1 :  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1 :  [[1.6]
 [1.6]]
w2 :  [[0.1]
 [0.1]]
b2 :  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [ ]:
X

array([[8],
       [8]])

In [ ]:
y

np.int64(4)

In [ ]:
# Calculate loss

(y- 0.32)**2

np.float64(13.5424)

In [ ]:
def update_parameters(parameters, y, y_hat, A1, X):
  parameters['w2'][0][0] = parameters['w2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['w2'][1][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['w1'][0][0] = parameters['w1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0]*X[0][0])
  parameters['w1'][0][1] = parameters['w1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][0][0])

  parameters['w1'][1][0] = parameters['w1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0]*X[0][0])
  parameters['w1'][1][1] = parameters['w1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['w2'][1][0])



In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = init_para([2,2,1])

y_hat, A1 = L_Layer_forward(X, parameters)


A0 :  [[8]
 [8]]
w1 :  [[0.1 0.1]
 [0.1 0.1]]
b1 :  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1 :  [[1.6]
 [1.6]]
w2 :  [[0.1]
 [0.1]]
b2 :  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [ ]:
y_hat = y_hat[0][0]
y_hat

np.float64(0.32000000000000006)

In [ ]:
A1

array([[1.6],
       [1.6]])

In [ ]:
update_parameters(parameters, y, y_hat, A1, X)

In [ ]:
parameters

{'w1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'w2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[1][0]

y_hat, A1 = L_Layer_forward(X, parameters)


A0 :  [[8]
 [8]]
w1 :  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1 :  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1 :  [[1.70612461]
 [1.70612461]]
w2 :  [[0.111776]
 [0.111776]]
b2 :  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************


In [ ]:
update_parameters(parameters, y, y_hat, A1, X)

/tmp/ipython-input-3155637935.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w2'][0][0] = parameters['w2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
/tmp/ipython-input-3155637935.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w2'][1][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
/tmp/ipython-input-3155637935.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['w2'][1][0] + (0.

In [ ]:
parameters

{'w1': array([[0.12599108, 0.12599108],
        [0.12599108, 0.12599108]]),
 'b1': array([[0.00324888],
        [0.00324888]]),
 'w2': array([[0.14248253],
        [0.14248253]]),
 'b2': array([[0.15148145]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[2][0]

y_hat, A1 = L_Layer_forward(X, parameters)
update_parameters(parameters, y, y_hat, A1, X)
parameters

A0 :  [[8]
 [8]]
w1 :  [[0.12599108 0.12599108]
 [0.12599108 0.12599108]]
b1 :  [[0.00324888]
 [0.00324888]]
----------------------------------------
A1:  [[2.01910609]
 [2.01910609]]
****************************************
A1 :  [[2.01910609]
 [2.01910609]]
w2 :  [[0.14248253]
 [0.14248253]]
b2 :  [[0.15148145]]
----------------------------------------
A2:  [[0.72685615]]
****************************************


/tmp/ipython-input-3155637935.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w2'][0][0] = parameters['w2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
/tmp/ipython-input-3155637935.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['w2'][1][0] = parameters['w2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
/tmp/ipython-input-3155637935.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['w2'][1][0] + (0.

{'w1': array([[0.13980896, 0.13980896],
        [0.13980896, 0.13980896]]),
 'b1': array([[0.00497612],
        [0.00497612]]),
 'w2': array([[0.16377661],
        [0.16377661]]),
 'b2': array([[0.17432289]])}

In [ ]:
# epochs Implementation
parameters = init_para([2,2,1])
epochs = 5

for j in range(epochs):
  loss = []  # Initialize loss list for each epoch
  for i in range(df.shape[0]):
    X =  df[['cgpa', 'profile_score']].values[i].reshape(-1,1) # Fixed: Access values before reshaping
    y = df[['lpa']].values[i][0]

    y_hat, A1 = L_Layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters, y, y_hat, A1, X)

    loss.append((y - y_hat) ** 2)

  print("Epoch: ", j+1, 'Loss - ', np.array(loss).mean())

A0 :  [[8]
 [8]]
w1 :  [[0.1 0.1]
 [0.1 0.1]]
b1 :  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1 :  [[1.6]
 [1.6]]
w2 :  [[0.1]
 [0.1]]
b2 :  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************
A0 :  [[7]
 [9]]
w1 :  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1 :  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1 :  [[1.70612461]
 [1.70612461]]
w2 :  [[0.111776]
 [0.111776]]
b2 :  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************
A0 :  [[ 6]
 [10]]
w1 :  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1 :  [[0.0019667]
 [0.0019667]]
----------------------------------------
A1:  [[1.83539945]
 [1.87200826]]
****************************************
A1 :  [[1.83539945]
 [1.87200826]]
w2 :  [[0.

## Using Keras


In [ ]:
import pandas as pd
import numpy as np

df= pd.DataFrame([[8,8,4], [7,9,5], [6,10,6],[5,12,7]], columns=['cgpa', 'profile_score','lpa'])


In [ ]:
import tensorflow
from tensorflow import keras
from keras.layers import Dense
from keras import Sequential

In [ ]:
model = Sequential()
model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(3, activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15 (60.00 B)

 Trainable params: 15 (60.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[ 1.0596634 , -0.3285463 ],
        [ 0.14339161, -0.08339345]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.4787976 , -0.1220296 ,  0.14473224],
        [-0.36098987, -0.60741556, -0.16532111]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1, 0.1],
                         [0.1,0.1]],
                        dtype=np.float32),
               np.array([0., 0.], # Changed shape to (2,) for the first layer bias
                        dtype=np.float32),
               np.array([[0.1,0.1,0.1], # Changed shape to (2,3) for the second layer weights
                         [0.1,0.1,0.1]],
                        dtype=np.float32),
               np.array([0., 0., 0.], dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1, 0.1, 0.1],
        [0.1, 0.1, 0.1]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)
model.build(input_shape=(None, 2)) # Explicitly build the model

In [ ]:
model.fit(df.iloc[:,0:-1].values, df.iloc[:,-1].values, epochs=75, verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 31.8194  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.1403 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.1258 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 28.5625 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 23.1388 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 30.0062 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 23.6836 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.0571 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.8143 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19.0731 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.8182 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.7833 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18.9175 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 18.5269 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17.9080
Epoch 16/75
4/4 ━━━

In [ ]:
model.get_weights()

[array([[0.3737077, 0.3737077],
        [0.3657214, 0.3657214]], dtype=float32),
 array([0.27240792, 0.27240792], dtype=float32),
 array([[0.37302297, 0.37302297, 0.37302297],
        [0.37302297, 0.37302297, 0.37302297]], dtype=float32),
 array([0.20481855, 0.20481855, 0.20481855], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)
model.build(input_shape=(None, 2)) # Explicitly build the model

In [ ]:
model.fit(df.iloc[:,0:-1].values, df.iloc[:,-1].values, epochs=75, verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 1.9887 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.6366 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.4784
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0274 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.7965
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.9439
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8517  
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6694 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1009 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3997 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7421 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7468 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7408 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8581 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.2522 
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━